[functions.send-school-verification]
enabled = true
verify_jwt = true
import_map = "./functions/send-school-verification/deno.json"
entrypoint = "./functions/send-school-verification/index.ts"

[functions.send-email-verification-code]
enabled = true
verify_jwt = false
import_map = "./functions/send-email-verification-code/deno.json"
entrypoint = "./functions/send-email-verification-code/index.ts"

[functions.verify-email-verification-code]
enabled = true
verify_jwt = false
import_map = "./functions/verify-email-verification-code/deno.json"
entrypoint = "./functions/verify-email-verification-code/index.ts"

[functions.complete-signup]
enabled = true
verify_jwt = false
import_map = "./functions/complete-signup/deno.json"
entrypoint = "./functions/complete-signup/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = false
import_map = "./functions/delete-account/deno.json"
entrypoint = "./functions/delete-account/index.ts"

[functions.translate-posts-worker]
enabled = false
verify_jwt = false
import_map = "./functions/translate-posts-worker/deno.json"
entrypoint = "./functions/translate-posts-worker/index.ts"
